const express=require("express");const path=require("path");const crypto=require("crypto");const {readSongs,writeSongs}=require("./data/store");
const app=express();const PORT=process.env.PORT||3000;const ADMIN_KEY=process.env.ADMIN_KEY||"change-this-admin-key";
app.use(express.json({limit:"1mb"}));app.use(express.static(path.join(__dirname,"public")));
function cleanSong(input){const sections=Array.isArray(input.lyrics)?input.lyrics:[];return{id:String(input.id||crypto.randomUUID()),title:String(input.title||"").trim(),lyricist:String(input.lyricist||"").trim(),singer:String(input.singer||"").trim(),category:String(input.category||"Other").trim(),dateAdded:String(input.dateAdded||new Date().toISOString().slice(0,10)),views:Number.isFinite(Number(input.views))?Number(input.views):0,lyrics:sections.map(s=>({type:s.type==="chorus"?"chorus":"verse",label:String(s.label||"").trim(),lines:Array.isArray(s.lines)?s.lines.map(String):[]}))};}
function admin(req,res,next){if((req.get("x-admin-key")||req.body?.adminKey)!==ADMIN_KEY)return res.status(401).json({error:"Unauthorized"});next();}
app.get("/api/config",(_req,res)=>res.json({facebookUrl:process.env.FACEBOOK_URL||"https://www.facebook.com/"}));
app.get("/api/songs",(req,res)=>{const q=String(req.query.q||"").trim().toLowerCase();let songs=readSongs();if(q)songs=songs.filter(s=>[s.title,s.lyricist,s.singer,s.category,...s.lyrics.flatMap(x=>x.lines)].join(" ").toLowerCase().includes(q));songs.sort((a,b)=>b.dateAdded.localeCompare(a.dateAdded));res.json(songs);});
app.get("/api/songs/top",(_req,res)=>res.json(readSongs().sort((a,b)=>b.views-a.views).slice(0,5)));
app.get("/api/songs/:id",(req,res)=>{const s=readSongs().find(x=>x.id===req.params.id);s?res.json(s):res.status(404).json({error:"Song not found"});});
app.post("/api/songs/:id/view",(req,res)=>{const songs=readSongs(),s=songs.find(x=>x.id===req.params.id);if(!s)return res.status(404).json({error:"Song not found"});s.views=Number(s.views||0)+1;writeSongs(songs);res.json({views:s.views});});
app.post("/api/songs",admin,(req,res)=>{const s=cleanSong(req.body);if(!s.title||!s.lyricist||!s.singer||!s.lyrics.length)return res.status(400).json({error:"Title, lyricist, singer and lyrics are required."});const songs=readSongs();if(songs.some(x=>x.id===s.id))s.id=crypto.randomUUID();songs.push(s);writeSongs(songs);res.status(201).json(s);});
app.put("/api/songs/:id",admin,(req,res)=>{const songs=readSongs(),i=songs.findIndex(x=>x.id===req.params.id);if(i<0)return res.status(404).json({error:"Song not found"});songs[i]=cleanSong({...songs[i],...req.body,id:songs[i].id});writeSongs(songs);res.json(songs[i]);});
app.delete("/api/songs/:id",admin,(req,res)=>{const songs=readSongs(),out=songs.filter(x=>x.id!==req.params.id);if(out.length===songs.length)return res.status(404).json({error:"Song not found"});writeSongs(out);res.json({ok:true});});
app.get("*",(_req,res)=>res.sendFile(path.join(__dirname,"public","index.html")));app.listen(PORT,()=>console.log("Mizo Lyrics running on port "+PORT));